### ISSUE TITLE
Using iLua in Objective-C

### ISSUE THREAD

**Issue by mrjm67** [profburke/ilua#3]
im tryng to Use iLua inside an Objective-C Project( LuaState Project Sample) But it seems Nothing Works Right.
imported the .c files and swift files , made class header  and import them inside .m File .

the result is full of  "Use of Unresolved identifire".

is it possible to make an objective c Sample ? or provide a tutorial for convert and use ilua inside objective c??

sorry for bad english.

**Comment by profburke** [comment]
If you want to use Lua in an Objective-C program, however, I would not use iLua. The point of iLua is to take advantage of Swift. So, if you are not using Swift, there are better approaches.

Using Lua with Objective-C should be pretty straight-forward, as there's really nothing to prevent you from directly calling the Lua API. However, if you'd like a little more structure, there are several CocoaPods that wrap Lua. Take a look at https://cocoapods.org/?q=lua

I have not used any of them, so I can not recommend any one over the other.
